/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppTraceRouteImport } from './routes/_app.trace'
import { Route as AppSupervisorsRouteImport } from './routes/_app.supervisors'
import { Route as AppMyCalculationRouteImport } from './routes/_app.my-calculation'
import { Route as AppMonthlyRouteImport } from './routes/_app.monthly'
import { Route as AppKpiUpdatesRouteImport } from './routes/_app.kpi-updates'
import { Route as AppKpiFrameworkRouteImport } from './routes/_app.kpi-framework'
import { Route as AppGradesRouteImport } from './routes/_app.grades'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppEmployeeRouteImport } from './routes/_app.employee'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditLogRouteImport } from './routes/_app.audit-log'
import { Route as AppAppraisalsReviewRouteImport } from './routes/_app.appraisals-review'
import { Route as AppAppraisalsRouteImport } from './routes/_app.appraisals'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTraceRoute = AppTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorsRoute = AppSupervisorsRouteImport.update({
  id: '/supervisors',
  path: '/supervisors',
  getParentRoute: () => AppRoute,
} as any)
const AppMyCalculationRoute = AppMyCalculationRouteImport.update({
  id: '/my-calculation',
  path: '/my-calculation',
  getParentRoute: () => AppRoute,
} as any)
const AppMonthlyRoute = AppMonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => AppRoute,
} as any)
const AppKpiUpdatesRoute = AppKpiUpdatesRouteImport.update({
  id: '/kpi-updates',
  path: '/kpi-updates',
  getParentRoute: () => AppRoute,
} as any)
const AppKpiFrameworkRoute = AppKpiFrameworkRouteImport.update({
  id: '/kpi-framework',
  path: '/kpi-framework',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeRoute = AppEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAppraisalsReviewRoute = AppAppraisalsReviewRouteImport.update({
  id: '/appraisals-review',
  path: '/appraisals-review',
  getParentRoute: () => AppRoute,
} as any)
const AppAppraisalsRoute = AppAppraisalsRouteImport.update({
  id: '/appraisals',
  path: '/appraisals',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/appraisals': typeof AppAppraisalsRoute
  '/appraisals-review': typeof AppAppraisalsReviewRoute
  '/audit-log': typeof AppAuditLogRoute
  '/dashboard': typeof AppDashboardRoute
  '/employee': typeof AppEmployeeRoute
  '/employees': typeof AppEmployeesRoute
  '/grades': typeof AppGradesRoute
  '/kpi-framework': typeof AppKpiFrameworkRoute
  '/kpi-updates': typeof AppKpiUpdatesRoute
  '/monthly': typeof AppMonthlyRoute
  '/my-calculation': typeof AppMyCalculationRoute
  '/supervisors': typeof AppSupervisorsRoute
  '/trace': typeof AppTraceRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/appraisals': typeof AppAppraisalsRoute
  '/appraisals-review': typeof AppAppraisalsReviewRoute
  '/audit-log': typeof AppAuditLogRoute
  '/dashboard': typeof AppDashboardRoute
  '/employee': typeof AppEmployeeRoute
  '/employees': typeof AppEmployeesRoute
  '/grades': typeof AppGradesRoute
  '/kpi-framework': typeof AppKpiFrameworkRoute
  '/kpi-updates': typeof AppKpiUpdatesRoute
  '/monthly': typeof AppMonthlyRoute
  '/my-calculation': typeof AppMyCalculationRoute
  '/supervisors': typeof AppSupervisorsRoute
  '/trace': typeof AppTraceRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_app/appraisals': typeof AppAppraisalsRoute
  '/_app/appraisals-review': typeof AppAppraisalsReviewRoute
  '/_app/audit-log': typeof AppAuditLogRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employee': typeof AppEmployeeRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/grades': typeof AppGradesRoute
  '/_app/kpi-framework': typeof AppKpiFrameworkRoute
  '/_app/kpi-updates': typeof AppKpiUpdatesRoute
  '/_app/monthly': typeof AppMonthlyRoute
  '/_app/my-calculation': typeof AppMyCalculationRoute
  '/_app/supervisors': typeof AppSupervisorsRoute
  '/_app/trace': typeof AppTraceRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-otp'
    | '/appraisals'
    | '/appraisals-review'
    | '/audit-log'
    | '/dashboard'
    | '/employee'
    | '/employees'
    | '/grades'
    | '/kpi-framework'
    | '/kpi-updates'
    | '/monthly'
    | '/my-calculation'
    | '/supervisors'
    | '/trace'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-otp'
    | '/appraisals'
    | '/appraisals-review'
    | '/audit-log'
    | '/dashboard'
    | '/employee'
    | '/employees'
    | '/grades'
    | '/kpi-framework'
    | '/kpi-updates'
    | '/monthly'
    | '/my-calculation'
    | '/supervisors'
    | '/trace'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/forgot-password'
    | '/reset-password'
    | '/verify-otp'
    | '/_app/appraisals'
    | '/_app/appraisals-review'
    | '/_app/audit-log'
    | '/_app/dashboard'
    | '/_app/employee'
    | '/_app/employees'
    | '/_app/grades'
    | '/_app/kpi-framework'
    | '/_app/kpi-updates'
    | '/_app/monthly'
    | '/_app/my-calculation'
    | '/_app/supervisors'
    | '/_app/trace'
    | '/_auth/login'
    | '/_auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/trace': {
      id: '/_app/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof AppTraceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisors': {
      id: '/_app/supervisors'
      path: '/supervisors'
      fullPath: '/supervisors'
      preLoaderRoute: typeof AppSupervisorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-calculation': {
      id: '/_app/my-calculation'
      path: '/my-calculation'
      fullPath: '/my-calculation'
      preLoaderRoute: typeof AppMyCalculationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monthly': {
      id: '/_app/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof AppMonthlyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpi-updates': {
      id: '/_app/kpi-updates'
      path: '/kpi-updates'
      fullPath: '/kpi-updates'
      preLoaderRoute: typeof AppKpiUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpi-framework': {
      id: '/_app/kpi-framework'
      path: '/kpi-framework'
      fullPath: '/kpi-framework'
      preLoaderRoute: typeof AppKpiFrameworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grades': {
      id: '/_app/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee': {
      id: '/_app/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AppEmployeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appraisals-review': {
      id: '/_app/appraisals-review'
      path: '/appraisals-review'
      fullPath: '/appraisals-review'
      preLoaderRoute: typeof AppAppraisalsReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appraisals': {
      id: '/_app/appraisals'
      path: '/appraisals'
      fullPath: '/appraisals'
      preLoaderRoute: typeof AppAppraisalsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppraisalsRoute: typeof AppAppraisalsRoute
  AppAppraisalsReviewRoute: typeof AppAppraisalsReviewRoute
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeeRoute: typeof AppEmployeeRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppGradesRoute: typeof AppGradesRoute
  AppKpiFrameworkRoute: typeof AppKpiFrameworkRoute
  AppKpiUpdatesRoute: typeof AppKpiUpdatesRoute
  AppMonthlyRoute: typeof AppMonthlyRoute
  AppMyCalculationRoute: typeof AppMyCalculationRoute
  AppSupervisorsRoute: typeof AppSupervisorsRoute
  AppTraceRoute: typeof AppTraceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppraisalsRoute: AppAppraisalsRoute,
  AppAppraisalsReviewRoute: AppAppraisalsReviewRoute,
  AppAuditLogRoute: AppAuditLogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeeRoute: AppEmployeeRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppGradesRoute: AppGradesRoute,
  AppKpiFrameworkRoute: AppKpiFrameworkRoute,
  AppKpiUpdatesRoute: AppKpiUpdatesRoute,
  AppMonthlyRoute: AppMonthlyRoute,
  AppMyCalculationRoute: AppMyCalculationRoute,
  AppSupervisorsRoute: AppSupervisorsRoute,
  AppTraceRoute: AppTraceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
